server:
  port: 8080

spring:
  main:
    allow-bean-definition-overriding: false
    allow-circular-references: true
    banner-mode: off
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.elasticsearch.ElasticsearchRestClientAutoConfiguration
  flyway:
    enabled: false
  datasource:
    url: jdbc:postgresql://farmsuite.org:5432/farmsuite?currentSchema=fhir
    username: postgres
    password: "YYw1k4Wqae"
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
  jpa:
    properties:
      hibernate:
        format_sql: false
        show_sql: false
        dialect: ca.uhn.fhir.jpa.model.dialect.HapiFhirPostgresDialect
        default_schema: fhir
        hbm2ddl:
          auto: update

hapi:
  fhir:
    fhir_version: R5
    openapi_enabled: true
    narrative_enabled: false
    bulk_export_enabled: false
    bulk_import_enabled: false
    mdm_enabled: false
    ig_runtime_upload_enabled: false
    search-coord-core-pool-size: 20
    search-coord-max-pool-size: 100
    search-coord-queue-capacity: 200
    search_prefetch_thresholds: 13,503,2003,-1
    cors:
      allowed_origin:
        - "*"
    cr:
      enabled: false
    cdshooks:
      enabled: false
    logical_urls:
      - http://terminology.hl7.org/*
      - https://terminology.hl7.org/*
      - http://snomed.info/*
      - https://snomed.info/*
      - http://unitsofmeasure.org/*
      - https://unitsofmeasure.org/*
      - http://loinc.org/*
      - https://loinc.org/*
    partitioning:
      allow_references_across_partitions: true
      partitioning_include_in_search_hashes: false
      request_tenant_partitioning_mode: true
      conditional-create-duplicate-identifiers-enabled: false
      database-partition-mode-enabled: true

sso:
  oidc:
    enabled: true
    issuer-uri: https://farmsuite.org/auth/realms/farmsuite
    public-paths:
      - /fhir/swagger-ui/**
      - /fhir/api-docs/**


logging:
  level:
    root: INFO
    org.farmsuite: DEBUG
