global:
  imagePullSecrets: []
  image:
    imagePullPolicy: Always
  httpRoute:
    enabled: true
    parentRefs:
      - name: gateway
        sectionName: https
    hostnames:
      - 'farmsuite.org'

replicaCount: 1

image:
  tag: "v8.6.0-1"

nameOverride: ""
fullnameOverride: ""

podAnnotations: {}
podLabels: {}

service:
  type: ClusterIP
  port: 8080

resources:
  requests:
    memory: "1Gi"
    cpu: "500m"
  limits:
    memory: "2Gi"
    cpu: "2000m"

livenessProbe:
  initialDelaySeconds: 30
  periodSeconds: 20

readinessProbe:
  initialDelaySeconds: 30
  periodSeconds: 20

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

tolerations: []
affinity: {}

http_relative_path: "/fhir"

applicationConfig: |
  server:
    servlet:
      context-path: /fhir
  port: 8080
  tomcat:
    relaxed-query-chars: "|"
  management:
    endpoints:
      enabled-by-default: false
      web:
        exposure:
          include: "health"
    endpoint:
      info:
        enabled: true
      metrics:
        enabled: true
      health:
        enabled: true
        probes:
          enabled: true
        group:
          liveness:
            include: [ "livenessState", "readinessState" ]
      prometheus:
        enabled: true
    prometheus:
      metrics:
        export:
          enabled: true
  spring:
    application:
      name: "HAPI"
    flyway:
      enabled: false
      baseline-on-migrate: true
      fail-on-missing-locations: false
    datasource:
      url: "jdbc:postgresql://localhost:5432/fhir"
      username: "fhir"
      password: ""
      driver-class-name: org.postgresql.Driver
      hikari:
        maximum-pool-size: 10
    jpa:
      properties:
        hibernate:
          dialect: ca.uhn.fhir.jpa.model.dialect.HapiFhirPostgresDialect
          hbm2ddl:
            auto: update
  hapi:
    fhir:
      fhir_version: R5
      use_apache_address_strategy: true
      openapi_enabled: true
      cr:
        enabled: false                            # exposes Clinical Reasoning operation endpoints
        caregaps:
          reporter: "default"
          section_author: "default"
        terminologyServerClientSettings:
          maxRetryCount: 3
          retryIntervalMillis: 1000
          timeoutSeconds: 30
          socketTimeout: 60
        cql:
          use_embedded_libraries: true
          compiler:
            error_level: Info
            signature_level: All
            enable_annotations: true
            enable_locators: true
            enable_results_type: true
            enable_detailed_errors: true
          runtime:
            debug_logging_enabled: false
            # enable_validation: false
            # enable_expression_caching: true
          terminology:
            valueset_preexpansion_mode: USE_IF_PRESENT
            valueset_expansion_mode: PERFORM_NAIVE_EXPANSION
            valueset_membership_mode: USE_EXPANSION
            code_lookup_mode: USE_VALIDATE_CODE_OPERATION
          data:
            search_parameter_mode: USE_SEARCH_PARAMETERS
            terminology_parameter_mode: FILTER_IN_MEMORY
            profile_mode: DECLARED
      bulk_export_enabled: false
      bulk_import_enabled: false
      bulk_export_file_retention_period_hours: 2
      narrative_enabled: false
      mdm_enabled: false
      mdm_rules_json_location: "mdm-rules.json"
      logical_urls:
        - http://terminology.hl7.org/*
        - https://terminology.hl7.org/*
        - http://snomed.info/*
        - https://snomed.info/*
        - http://unitsofmeasure.org/*
        - https://unitsofmeasure.org/*
        - http://loinc.org/*
        - https://loinc.org/*
      cors:
        allowed_origin:
          - "*"
      search-coord-core-pool-size: 20
      search-coord-max-pool-size: 100
      search-coord-queue-capacity: 200
      search_prefetch_thresholds: 13,503,2003,-1
      binary_storage_minimum_binary_size: 4000

extraEnv: []

volumes: []
volumeMounts: []
